FROM debian:12-slim

ENV DEBIAN_FRONTEND=noninteractive

# Install all languages & tools
RUN apt update -y && apt install -y \
    python3 python3-pip \
    nodejs npm \
    openjdk-17-jdk-headless \
    gcc g++ \
    golang-go \
    bash \
    coreutils \
    build-essential \
    && apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app