FROM debian:12-slim

ENV DEBIAN_FRONTEND=noninteractive

# Install all languages & tools
RUN apt update -y && apt install -y \
    python3 python3-pip \
    nodejs npm \
    openjdk-17-jdk-headless \
    gcc g++ \
    golang-go \
    bash \
    coreutils \
    docker.io \
    build-essential \
    && apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Create temp directory for code execution
RUN mkdir -p /app/temp && chmod 777 /app/temp